### ISSUE TITLE
无法部署

### ISSUE THREAD

**Issue by SuperChenSSS** [sitexa/anires#1]
如题，按照README.md方法部署后，打开页面为空白

**Comment by sitexa** [comment]
删除dist/index.html,里面有硬编码。

**Comment by huadada** [comment]
think you

**Comment by CarlosPython** [comment]
hi,南方
$ git push
remote: Permission to sitexa/anires.git denied to CarlosPython.
fatal: unable to access 'https://github.com/sitexa/anires.git/': The requested URL returned error: 403
部署不知到是哪里出了点点问题~
