### ISSUE TITLE
希望有点职业精神，借鉴代码连出处都不写

### ISSUE THREAD

**Issue by johnwatsondev** [sitexa/anires#5]
本来不想开这个 issue，但是同为技术人，实在不敢恭维您的做法，技术再牛逼，做人的基本底线还是要有的，您说是吧？

更为要命的是这简直就是抄袭，抄袭都不写出处，真的厉害。

况且原项目都没有给出开源许可证，在下佩服。

出处在此：https://github.com/jirengu-inc/animating-resume

**Comment by sitexa** [comment]
为了发布才放在这里.后来想想放出处,又没找到.并无恶意,并非牛人,仅为找份苦逼的差事糊口.多谢指教,立马改正.
